### ISSUE TITLE
The adb process returned error code -1 

### ISSUE THREAD

**Issue by flashbear** [SharpAdb/AdvancedSharpAdbClient#104]
### What can we do for you?

I'm keeping getting an error code -1 when running command start-server using the example code below:
This code works only if I initiate the server manually first (ex. by running 'adb devices') via command prompt which starts the server.
any idea?  my adb path is correct

![error](https://github.com/SharpAdb/AdvancedSharpAdbClient/assets/62415374/8c252067-70b0-40ac-977f-cb827910ac6e)

**Comment by wherewhere** [comment]
Fixed #103
