### ISSUE TITLE
We need a better documentation for the library

### ISSUE THREAD

**Issue by schizoidcock** [SharpAdb/AdvancedSharpAdbClient#11]
i like this project and i had been using recently to do some stuff with phones, but actually we need a better readable documentation because the library has a ton of stuff. But we lose a lot of time trying to understand how of some of the funtionality works with it because there is no documentation avalaible for it.

**Comment by schizoidcock** [comment]
@yungd1plomat any answer on this man?

**Comment by UhWatchMe** [comment]
I'm new to this library and it's pretty difficult for me to go through, as I have to do 
`device = client.GetDevices()[0];`
instead of `device = client.GetDevices().FirstOrDefault();`

Also the xpath I can't wrap my head around it, how do I even retreive data if it's not working.
