### ISSUE TITLE
May I ask how to execute adb tcpip 5555 and other adb commands without predefined methods? Thank you!

### ISSUE THREAD

**Issue by rvhome** [SharpAdb/AdvancedSharpAdbClient#62]
### Describe your question

May I ask how to execute adb tcpip 5555 and other adb commands without predefined methods? Thank you!

**Comment by wherewhere** [comment]
I am not sure it can work. 
```cs
using IAdbSocket socket = adbSocketFactory(EndPoint); 
await socket.SendAdbRequestAsync("host:tcpip:5555", cancellationToken); 
AdbResponse response = await socket.ReadAdbResponseAsync(cancellationToken); 
string result = await socket.ReadStringAsync(cancellationToken);
```
Mybe you can direct excuse adb.exe through Process.

**Comment by rvhome** [comment]
Thank you for returning the unknown host service. After removing host:, there is no return value, so we can only use process first
