### ISSUE TITLE
How to execute simple adb commands not abd shell ones?

### ISSUE THREAD

**Issue by Chicagorange** [SharpAdb/AdvancedSharpAdbClient#65]
### What can we do for you?

Hello,

Is there a way to send simple adb commands?

I would like to retrieve a folder from my device but I can't find a way to do it.

Thank you.

**Comment by wherewhere** [comment]
This project is direct communicate with adb service. If you want to communicate with adb client, just use `Process` to send command.

**Comment by Chicagorange** [comment]
Thanks for your quick reply.

Actually I don't know the difference between adb shell and adb but I have been able to send my command using `Process`.
That was my previous solution to send adb and adb shell commands. I just thought that I could send all commands using AdvancedSharpAdbClient.
