### ISSUE TITLE
Additional information: An error occurred while receiving xml: ERROR: null root node returned by UiTestAutomationBridge.

### ISSUE THREAD

**Issue by mrjay59** [SharpAdb/AdvancedSharpAdbClient#81]
### What can we do for you?

![image](https://github.com/SharpAdb/AdvancedSharpAdbClient/assets/66785677/a1900e8b-2988-4955-bfa3-fbc2245807cc)

AdvancedSharpAdbClient v2.5.8

how to fix ..?

**Comment by wherewhere** [comment]
Can't fix. It's an error from ADB.

**Comment by mrjay59** [comment]
ok sir
