### ISSUE TITLE
An error occurred while receiving xml: ERROR: null root node returned

### ISSUE THREAD

**Issue by mrjay59** [SharpAdb/AdvancedSharpAdbClient#84]
### Describe the bug

I always find this bug when searching for elements

```vbnet
Dim Elspgsuara = Adb.FindElement("//node[@text='Mulai panggilan suara?']") 
```

for the device
![image](https://github.com/SharpAdb/AdvancedSharpAdbClient/assets/66785677/a001b477-a29f-4066-910a-1ae1c09d9535)

how to solve it if node is null

### Steps to reproduce the bug

```vbnet
Dim elEndC = Adb.FindElement($"//node[@resource-id='com.{whatsapp}:id/footer_end_call_btn']")
If (elEndC Is Nothing) Then
    Dim Elspgsuara = Adb.FindElement("//node[@text='Mulai panggilan suara?']") 'bar ic VOICE

    If Not (Elspgsuara Is Nothing) Then
        Thread.Sleep(500)
        KlikTouch("PAG", whatsapp)
    End If

    Dim Elstpaggil = Adb.FindElement("//node[@text='Pilih tipe panggilan']") 'bar ic VOICE

    If Not (Elstpaggil Is Nothing) Then
        Thread.Sleep(500)
        KlikTouch("PS1", whatsapp)
    End If
End If
```

### Expected behavior

No response

### Screenshots

No response

### NuGet package version

Latest Source

### .NET Platform

.NET Framework 4.5.x

### Platform type

Windows

### System version

windows 10

### IDE

Visual Studio 2015

**Comment by wherewhere** [comment]
@yungd1plomat

**Comment by yungd1plomat** [comment]
There could be many reasons. Please attach xml from the DumpScreenString method:
```C#
var client = new AdbClient();
var device = client.GetDevices().First();
var screen = client.DumpScreenString(device);
await File.WriteAllTextAsync("node.xml", screen);
```

**Comment by mrjay59** [comment]
oke sir
